### PR TITLE
Tulpas in endless war

### PR DESCRIPTION
**Pull request by ghost**
Cool and new update, breaks new grounds. 

You can now have tulpas in endless war.

### CODE REVIEW

**Comment by magicksRampage** [comment]
tired: using tulpas as an excuse for gameplay alts

wired: making other players your tulpas

**Comment by mudkipslaps** [comment]
The funny thing to me is that you assigned webbed feet a description a second time. Silly tulpas

**Comment by ghost** [comment]
Making other players your tulpa is the mindbreak mutation.

**Comment by ghost** [comment]
I dont know how to make other players your tulpa.

**Comment by mudkipslaps** [comment]
rip ghost

**Comment by magicksRampage** [comment]
DENIED

**Pull request closed without merging**
