### PR TITLE
update time_lastenter of users only after roles have been updated to …

### PR DESCRIPTION
**Pull request by MeatyLearner**
…avoid unfair enemy deaths

### CODE REVIEW

**Comment by magicksRampage** [comment]
won't this actually make things worse? players might get attacked while discord is updating their roles, cause the game will think they've been in the new district for much longer

**Comment by MeatyLearner** [comment]
yeah i didn't think about that, maybe it's better to just add 5 or so seconds to time_lastenter before the roles are updated

**Comment by magicksRampage** [comment]
we already have an aggro timer. we can just increase time_enemyaggro. but you know what would really be better? changing the combat system so a few seconds of lag aren't as big a deal. !dab

**Comment by MeatyLearner** [comment]
damn... well yes, how do you propose we change enemy combat for that? i'm assuming the horseman boss is supposed to kill in one shot, so lowering damage wouldn't be a good fix for this situation

**Comment by magicksRampage** [comment]
is... is that a trick question? I've already proposed a whole new combat system. SAP + captchas

**Comment by MeatyLearner** [comment]
oh, well, SAP yes but enemies don't have captchas right?

**Comment by magicksRampage** [comment]
oh for enemies we can just decrease their dps to match the lower dps of captcha combat

**Comment by magicksRampage** [comment]
the horseman only has to one-shot you currently, cause combat is so damn fast

**Comment by MeatyLearner** [comment]
alright, fair

**Pull request closed without merging**
