### PR TITLE
Update ewcmd.py

### PR DESCRIPTION
**Pull request by ghost**
Minor fix for the game to address some playability problems with the `!harvest` command.

### CODE REVIEW

**Comment by minervatbd** [comment]
krak worst dev

**Comment by EthanStraub** [comment]
You're out of your element.

**Comment by minervatbd** [comment]
_krakissi_: **HARVEST IS NOT A COMMAND YOU FUCKING IDIOT.**

**Comment by ghost** [comment]
You hate to see it...

**Comment by mudkipslaps** [comment]
2019 Colourized - Old Game dev loses his marbles

**Comment by ghost** [comment]
Screenshot from 2019-12-09 13-19-11
Screenshot from 2019-12-09 12-59-37

I have acquired the slime. It is time for slimebois to share in the bounty.

`!harvest` is and has always been a command.

**Comment by ghost** [comment]
thank u

**Pull request merged**
